### ISSUE TITLE
Email - Automate from HPM SMART for notifications for PPSN Exceptions

### ISSUE THREAD

**Issue by Wilsonhpm** [hpm-networks/hpmsmart#183]
Need to automate emails from HPM SMART for PPSN: Parts per serial number exceptions directly to HP PSDM Representative. We are currently doing these manually but will need to automate this process since we will be removing Glenn from the call.

**Comment by Wilsonhpm** [comment]
As Sabur discussed, lets have this reference the Project Coordinator, creating an UI for this would be really nice to have and tie into this process. Please let me know if there are questions.

**Comment by hpm-networks** [comment]
I want clarity on this topic.

**Comment by hpm-networks** [comment]
UI, controller and database change for Expiring Claims with claim remove option is complete. I am testing this at my localhost.

**Comment by hpm-networks** [comment]
UI and database change with Delete option is complete and pushed into production. now working on the email notification.
