### ISSUE TITLE
UI - DC Operator/Partner Inventory specialist - visibility only to their assigned datacenter

### ISSUE THREAD

**Issue by Wilsonhpm** [hpm-networks/hpmsmart#21]
"We should be setting restrictions to these roles:

DC Operator
Partner Inventory specialist

to only see their datacenter and not others."

"can you please tell for which features do you want these changes, like claims, ticket management, service records etc.
they would have the same access but only narrowed down to see their specific datacenter and not all the customers."

**Comment by hpm-networks** [comment]
customer manager can only assign rights to his team on his datacenters only and not other customers datacenters.
