### ISSUE TITLE
HPE cancelling and reordering claim - making sure that all info is filled out for claim submission

### ISSUE THREAD

**Issue by Wilsonhpm** [hpm-networks/hpmsmart#222]
There was a claim that we received an invoice for, it is claim XC25979677. It is for SR-223064, shows that this was POD on 6/24/16 but the claim status was never changed causing it to expire, also I noticed that the DMR option was not checked off which it should’ve been. Can you please look into this and get it addressed?

**Comment by hpm-networks** [comment]
I have checked the code and it looks good. I am monitoring the claims daily and the processing seems good too. there is sometime unexpected behavior from hp csn and its response is different.

**Comment by Wilsonhpm** [comment]
after discussion, this relates more to filling out complete information for completed claims and claims submitted. when HPE cancelled and reorderd claims causing the issue with incomplete information. I will go ahead and update the header
