### ISSUE TITLE
HP CSN - Update Criteo End User information

### ISSUE THREAD

**Issue by Wilsonhpm** [hpm-networks/hpmsmart#224]
Hi Irfan,

can you please update the End User information for the company Criteo? HP will not allow us to use the France address since it is outside of country and violates warranty support contract.

Here is the new address:

End User Company: Criteo
End User name: Damien Michau
End User email: d.michau@criteo.com
End User phone: (650) 322-6260
Address: 555 University Ave, Palo Alto, CA 94301

**Comment by hpm-networks** [comment]
Task is complete and database records updated.
