### ISSUE TITLE
UI - Claims - after 4 days claims tab

### ISSUE THREAD

**Issue by Wilsonhpm** [hpm-networks/hpmsmart#42]
I would like to have an expiring claims tab to view. I know that we have an alert notification for expiring claims but i would like to view that somewhere within HPM SMART.

**Comment by hpm-networks** [comment]
Ok I am evaluating the change effect.

**Comment by hpm-networks** [comment]
the Change is almost complete and I am doing QA.

**Comment by hpm-networks** [comment]
Task is complete and pushed into production.
